# Generated by Django 5.2.4 on 2025-07-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(verbose_name=0)),
                ('precio_costo', models.IntegerField(help_text='Valor en centavos')),
                ('precio_venta', models.IntegerField(help_text='Valor en centavos')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='productos', to='inventario.etiqueta')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='talleres.taller')),
            ],
        ),
    ]
