# Generated by Django 5.2.4 on 2025-08-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
