# Generated by Django 5.2.4 on 2025-07-18 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('talleres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAR', 'Consultar'), ('LOGIN', 'Iniciar sesión'), ('LOGOUT', 'Cerrar sesión')], max_length=20)),
                ('modelo_afectado', models.CharField(max_length=50)),
                ('id_objeto', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('INGRESO', 'Ingreso de stock'), ('SALIDA', 'Salida de stock'), ('AJUSTE', 'Ajuste de inventario'), ('TRASLADO', 'Traslado entre talleres')], max_length=20)),
                ('cantidad_anterior', models.PositiveIntegerField()),
                ('cantidad_nueva', models.PositiveIntegerField()),
                ('cantidad_cambiada', models.IntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_inventario', to='inventario.producto')),
                ('taller_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_destino', to='talleres.taller')),
                ('taller_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_origen', to='talleres.taller')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_inventario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
